TrashCollector/Controllers/CustomersController.cs
using Google.Maps;
using Google.Maps.Geocoding;
using Google.Maps.StaticMaps;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Xml.Linq;
using TrashCollector.Models;

namespace TrashCollector.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        public ActionResult Index()
        {
            FilterViewModel model = new FilterViewModel();
            model.DayWeek = new SelectList(new List<string> { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" });
            model.Customers = db.Customers.Include(e => e.ApplicationUser).ToList();
            var mapUri = Map(model.Customers, "United States");
            ViewBag.StaticMapUri = mapUri;
            return View(model);
        }
        [HttpPost]
        public ActionResult Index(FilterViewModel model)
        {
            var viewModel = PeopleFilter(model.Day);
            return View("Index", viewModel);
        }
        public ActionResult Balance()
        {
            var Id = User.Identity.GetUserId();
            var person = db.Customers.Include(c => c.ApplicationUser).Where(c => c.ApplicationId == Id).Select(c => c).SingleOrDefault();
            return View(person);
        }
        public FilterViewModel PeopleFilter(string day)
        {
            FilterViewModel model = new FilterViewModel();
            model.DayWeek = new SelectList(new List<string> { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" });
            var Id = User.Identity.GetUserId();
            var user = db.Employees.Where(e => e.ApplicationId == Id).Select(e => e).SingleOrDefault();
            model.Day = day;
            model.Customers = db.Customers.Include(c => c.ApplicationUser).Where(c => c.PickupDay == day && c.Zip == user.Zip).Select(c => c).ToList(); // add extra pickup date
            return model;
        }
        public string Map(List<Customer> customers, string location)
        {
            if (customers != null && customers.Count > 0)
            {
                var zip = location;
                var zoom = 13;
                string markers = "";
                List<string> addresses = new List<string>();
                foreach (var customer in customers)
                {
                    if (customer.Lng == null || customer.Lat == null)
                    {                        
                        string requestUri = string.Format("https://maps.googleapis.com/maps/api/geocode/xml?key={1}&address={0}&sensor=false", Uri.EscapeDataString(customer.Address), "AIzaSyCGKMApsiQJT - YV_KWIV63HXtTMITjhPiw");
                        WebRequest request = WebRequest.Create(requestUri);
                        WebResponse response = request.GetResponse();
                        XDocument xdoc = XDocument.Load(response.GetResponseStream());
                        XElement result = xdoc.Element("GeocodeResponse").Element("result");
                        if (result != null)
                        {
                            XElement locationElement = result.Element("geometry").Element("location");
                            XElement lat = locationElement.Element("lat");
                            XElement lng = locationElement.Element("lng");
                            customer.Lat = lat.Value;
                            customer.Lng = lng.Value;
                            db.SaveChanges();
                        }
                    }
                }
                foreach (var item in customers)
                {
                    markers += "markers=color:red%7Clabel:C%7C" + item.Lat + "," + item.Lng + "&";
                }
                if (location == "United States")
                {
                    zoom = 4;
                }
                string mapUri = string.Format("https://maps.googleapis.com/maps/api/staticmap?center={0}&zoom={3}&size=650x350&maptype=roadmap&{2}key={1}", Uri.EscapeDataString(zip), "AIzaSyCGKMApsiQJT - YV_KWIV63HXtTMITjhPiw", markers, zoom);
                return mapUri;
            }
            return "";
        }

        public ActionResult Filter()
        {
            var today = Convert.ToString(DateTime.Now.DayOfWeek);
            var model = PeopleFilter(today);
            string zip;
            if (model.Customers == null || model.Customers.Count == 0)
            {
                zip = "";
            }
            else
            {
                zip = model.Customers[0].Zip;
            }
            var mapUri = Map(model.Customers, zip);
            ViewBag.StaticMapUri = mapUri;
            return View("Index", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Filter(FilterViewModel model)
        {
            var filterModel = PeopleFilter(model.Day);
            string zip;
            if (model.Customers == null || model.Customers.Count == 0)
            {
                zip = "";
            }
            else
            {
                zip = model.Customers[0].Zip;
            }
            var mapUri = Map(filterModel.Customers, zip);
            ViewBag.StaticMapUri = mapUri;
            return View("Index", filterModel);
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id, Messages? messages, string value)
        {
            Customer customer;
            List<Customer> customers = new List<Customer>();
            ViewBag.Message =
                messages == Messages.RegisterPickup ? "Your order was placed! Thank you for choosing 'Super Garbo-Men' to be your designated trash collectors."
                : messages == Messages.RegisterOtherPickup ? "Your order was placed! We will come pick-up on those desire days."
                : "";
            if (User.IsInRole("Customer") == true)
            {
                var currentId = User.Identity.GetUserId();
                customer = db.Customers.Include(c => c.ApplicationUser).Where(e => e.ApplicationId == currentId).Select(e => e).SingleOrDefault();
                customer.CanSee = value;
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                customer = db.Customers.Include(c => c.ApplicationUser).Where(c => c.Id == id).SingleOrDefault();
                if (customer == null)
                {
                    return HttpNotFound();
                }
            }
            customers.Add(customer);
            var mapUri = Map(customers, customers[0].Zip);
            ViewBag.StaticMapUri = mapUri;
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Zip,Address,FirstName,LastName,State,City,Balance,PickupDay,ExtraPickupDate,SuspendedStart,SuspendedEnd,ApplicationId")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                var Id = User.Identity.GetUserId();
                customer.ApplicationId = Id;
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("LogOut", "Account");
            }
            ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Email", customer.ApplicationId);
            return View(customer);
        }

        public ActionResult Register()
        {
            var Id = User.Identity.GetUserId();
            var person = db.Customers.Where(c => c.ApplicationId == Id).Select(c => c).SingleOrDefault();
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Customer customer)
        {
            try
            {
                var personId = User.Identity.GetUserId();
                var personToEdit = db.Customers.Where(c => c.ApplicationId == personId).Select(c => c).SingleOrDefault();
                var tempHolder = personToEdit.PickupDay;
                personToEdit.PickupDay = customer.PickupDay;
                personToEdit.ExtraPickupDate = customer.ExtraPickupDate;
                personToEdit.SuspendedStart = customer.SuspendedStart;
                personToEdit.SuspendedEnd = customer.SuspendedEnd;
                if (customer.PickupDay != null && customer.PickupDay != tempHolder)
                {
                    db.SaveChanges();
                    return RedirectToAction("Details", new { value = "false", message = Messages.RegisterPickup });
                }
                else
                {
                    personToEdit.PickupDay = tempHolder;
                }
                if (customer.ExtraPickupDate != null || (customer.SuspendedEnd != null && customer.SuspendedStart != null))
                {
                    db.SaveChanges();
                    return RedirectToAction("Details", new { value = "false", message = Messages.RegisterOtherPickup });
                }
                return RedirectToAction("Details", new { value = "false" });
            }
            catch (Exception)
            {
                return View(customer);
            }
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {

TrashCollector/Controllers/RoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrashCollector.Models;

namespace TrashCollector.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context;
        public RoleController()
        {
            context = new ApplicationDbContext();
        }
        // GET: Role
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            var Roles = context.Roles.ToList();
            return View(Roles);
        }
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
        public ActionResult Create()
        {
            return View();
        }
    }
}

TrashCollector/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Garbo-Men</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="background-image:url(../../Content/architecture-building-exterior-buildings-1389339.jpg); background-size:cover">
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:cornflowerblue; opacity:.9">
        <div class="container-fluid" style="">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p style="font-weight:bold; font-style:italic">@Html.ActionLink("Garbo-Men", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</p>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown" style="font-weight:600"> Options <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            @if (User.IsInRole("Admin") == true)
                            {
                                <li> @Html.ActionLink("Home", "Index", "Home")</li>
                                <li class="divider"></li>
                                <li> @Html.ActionLink("All Users", "Index", "Employees")</li>
                                <li class="divider"></li>
                                <li> @Html.ActionLink("Add Employee", "Index", "Role")</li>
                            }
                            else if (User.IsInRole("Manager") == true)
                            {
                                <li> @Html.ActionLink("Home", "Index", "Employees")</li>
                                <li class="divider"></li>
                                <li> @Html.ActionLink("Pick-up Orders", "Filter", "Customers")</li>
                            }
                            else if (User.IsInRole("Employee") == true)
                            {
                                <li> @Html.ActionLink("Home", "Filter", "Customers")</li>
                                <li> @Html.ActionLink("All Pick-up Orders", "Index", "Customers")</li>
                            }
                            else if (User.IsInRole("Customer") == true)
                            {
                                <li> @Html.ActionLink("Balance", "Balance", "Customers")</li>
                                <li class="divider"></li>
                                <li> @Html.ActionLink("Register/Edit Pick-up", "Register", "Customers")</li>
                            }
                            else
                            {
                                <li> @Html.ActionLink("Home", "Index", "Home")</li>
                            }
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown" style="font-weight:600"> Company Info <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="color:antiquewhite">&copy; @DateTime.Now.Year - Garbo-Men Inc.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>